#!/usr/bin/env python3
"""Bundle Chord Tone Finder into one self-contained .qml file.

Development keeps the logic in chordtones.js (music theory) and scan.js (reads the
score), imported by chord-tone-finder.qml. For installing, one file is nicer.

A QML object body only accepts property and function declarations, so both modules
go inside one IIFE assigned to a single property:

    property var lib: (function () {
        …chordtones.js…   var CT = { parseChord: parseChord, … };
        …scan.js…         var SC = { analyse: analyse, … };     // can call CT.foo
        return { CT: CT, SC: SC };
    })()

and the QML body's `SC.foo` becomes `lib.SC.foo`. The property name must start with
a lowercase letter — a capitalised one fails with only "Component is not ready".

Output: dist/ChordToneFinder.qml (git-ignored; run this script to rebuild it).
"""
import os, re

HERE = os.path.dirname(os.path.abspath(__file__))
DIST = os.path.join(HERE, 'dist')
MODULES = [('CT', 'chordtones.js'), ('SC', 'scan.js')]
LIB = 'lib'
QMLS = [('chord-tone-finder.qml', 'ChordToneFinder.qml')]


def module_source(path):
    src = open(path, encoding='utf-8').read()
    src = re.sub(r'^\s*\.pragma\s+library\s*$', '', src, flags=re.M)
    src = re.sub(r'^\s*\.import\s+.*$', '', src, flags=re.M)
    return src.strip()


def exported_names(src):
    names = re.findall(r'^function\s+([A-Za-z_]\w*)\s*\(', src, flags=re.M)
    names += re.findall(r'^var\s+([A-Za-z_]\w*)\s*=', src, flags=re.M)
    return list(dict.fromkeys(names))


def indent(text, spaces):
    pad = ' ' * spaces
    return '\n'.join(pad + line if line.strip() else line for line in text.split('\n'))


def library_block():
    parts = ['    property var %s: (function () {' % LIB]
    for prefix, fname in MODULES:
        src = module_source(os.path.join(HERE, fname))
        parts.append(indent('// ---- %s ----' % fname, 8))
        parts.append(indent(src, 8))
        table = ', '.join('%s: %s' % (n, n) for n in exported_names(src))
        parts.append(indent('var %s = { %s };' % (prefix, table), 8))
    parts.append(indent('return { %s };' % ', '.join('%s: %s' % (p, p) for p, _ in MODULES), 8))
    parts.append('    })()')
    return '\n'.join(parts)


def build():
    lib = library_block()
    os.makedirs(DIST, exist_ok=True)
    written = []
    for src_name, out_name in QMLS:
        text = open(os.path.join(HERE, src_name), encoding='utf-8').read()
        text = re.sub(r'^\s*import\s+"[\w-]+\.js"\s+as\s+\w+\s*\n', '', text, flags=re.M)
        for prefix, _ in MODULES:            # qualify before pasting the library in
            text = re.sub(r'(?<![\w.])%s\.([A-Za-z_]\w*)' % prefix,
                          lambda m, p=prefix: '%s.%s.%s' % (LIB, p, m.group(1)), text)
        text = re.sub(r'(MuseScore\s*\{\n)', lambda m: m.group(1) + lib + '\n\n', text, count=1)
        header = ('// Chord Tone Finder — generated by bundle.py, do not edit.\n'
                  '// Sources live in plugin/. Self-contained: no companion .js files needed.\n')
        path = os.path.join(DIST, out_name)
        open(path, 'w', encoding='utf-8').write(header + text)
        written.append(path)
    return written


if __name__ == '__main__':
    for p in build():
        print('wrote %s (%d bytes)' % (p, os.path.getsize(p)))
